# These will be overridden by the publish workflow and set to the new tag
name-template: "Next Release"
tag-template: "next"

exclude-labels:
  - kubectl-ng
categories:
  - title: "🚨 Breaking"
    label: "breaking"
  - title: "Enhancements"
    label: "enhancement"
  - title: "Bug Fixes"
    label: "bug"
  - title: "Documentation"
    label: "documentation"
  - title: "Project Hygiene"
    labels:
      - "ci"
      - "hygiene"

change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

template: |
  ## Changes

  $CHANGES  
