blank_issues_enabled: false
contact_links:
  - name: General Coding Question
    about: "If you have a question like *How do I scale a Deployment with kr8s?* you can also ask on Stack Overflow using the #kr8s tag."
    url: https://stackoverflow.com/questions/tagged/kr8s
