name: Feature Request
description: Request a feature
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        What would you like to see added?
  - type: dropdown
    id: project
    attributes:
      label: Which project are you requesting an enhancement for?
      multiple: false
      options:
        - kr8s
        - kubectl-ng
    validations:
      required: true
  - type: textarea
    id: what-do-you-need
    attributes:
      label: What do you need?
      description: What would you like to see added?
      placeholder: Tell us what you would like to see!
    validations:
      required: true
