# SPDX-FileCopyrightText: Copyright (c) 2024, Kr8s Developers (See LICENSE for list)
# SPDX-License-Identifier: BSD 3-Clause License
# Update sync code stubs
import ast

with open("kr8s/objects.py") as source_fh:
    source = source_fh.read()
    tree = ast.parse(source)

    # Update module docstring
    if isinstance(tree.body[0], ast.Expr) and isinstance(
        tree.body[0].value, ast.Constant
    ):
        tree.body[
            0
        ].value.value += (
            "\nNOTE: This typing stub file was generated by ci/gen_stubs.py\n"
        )
        tree.body[0].value.value += "DO NOT MODIFY DIRECTLY\n"

    tree.body[1].level = 1

    with open("kr8s/objects_tmp.pyi", "w") as target_fh:
        target_fh.write(ast.unparse(tree))
