name: "Pull Request Labeler"
on:
- pull_request_target

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4
      name: File Path Labeler
    - uses: TimonVS/pr-labeler-action@v5
      name: Conventional Commits Labeler
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        configuration-path: .github/conventional-commits-labeler.yml
