name: Publish to PyPI
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  publish-kr8s:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/kr8s
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build package
        run: pipx install hatch && hatch build
      - name: Publish kr8s
        uses: pypa/gh-action-pypi-publish@release/v1
  publish-kubectl-ng:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish kubectl-ng
        uses: JRubics/poetry-publish@v1.16
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN_KUBECTL_NG }}
          poetry_version: ==1.4.0
          plugins: "poetry-dynamic-versioning-plugin"
          package_directory: "examples/kubectl-ng"
