name: "Update Kubernetes"
on:
  schedule:
    - cron:  '30 2 * * *'
  workflow_dispatch: {}

jobs:
  update-kubernetes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install ruamel.yaml
      - name: Update Kubernetes
        run: ./ci/update-kubernetes.py
      - name: Show diff
        run: git diff
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        if: github.repository == 'kr8s-org/kr8s'
        with:
          base: main
          commit-message: "Update Kubernetes versions"
          title: "Update Kubernetes versions"
          reviewers: "jacobtomlinson"
          token: "${{ secrets.BOT_TOKEN }}"
          labels: "automerge"
          branch: "upgrade-k8s-version"
          body: |
            A new Kubernetes version has been detected.

            Updated CI and README badges.
