name: "Update Kubernetes"
on:
  schedule:
    - cron:  '30 2 * * *'
  workflow_dispatch: {}
  pull_request:
    paths:
      - .github/workflows/update-kubernetes.yaml
      - ci/update-kubernetes.py

jobs:
  update-kubernetes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install ruamel.yaml
      - name: Update Kubernetes
        run: ./ci/update-kubernetes.py
      - name: Show diff
        id: diff
        run: |
          echo 'diff<<EOF' >> $GITHUB_OUTPUT
          git diff | tee -a $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
      - name: Check if PR is needed
        id: pr-needed
        run: |
          echo "Diff: ${{ steps.diff.outputs.diff }}"
          if [ -z "${{ steps.diff.outputs.diff }}" ]; then
            echo "No changes to commit"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "Changes to commit"
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi
      - name: Generate PR title
        uses: ai-action/ollama-action@v1
        if: ${{ steps.pr-needed.outputs.has_changes }} == 'true'
        id: title-llm
        with:
          model: llama3.2
          prompt: |
            Generate a PR title for the following changes:

            ```
            ${{ steps.diff.outputs.diff }}
            ```
            The title should be concise and to the point, and should not include any markdown formatting.
            The title should be in the format of "Update Kubernetes version: remove 1.27" or similar.
            The title should be no more than 50 characters.
            The title should be in the present tense.
            The title is:
      - name: Show PR title
        if: ${{ steps.pr-needed.outputs.has_changes }} == 'true'
        run: |
          echo "The action would generate the following PR title: ${{ steps.title-llm.outputs.response }}"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        if: ${{ steps.pr-needed.outputs.has_changes }} == 'true' && github.repository == 'kr8s-org/kr8s' && github.ref == 'refs/heads/main'
        with:
          base: main
          commit-message: ${{ steps.title-llm.outputs.response }}
          title: ${{ steps.title-llm.outputs.response }}
          reviewers: "jacobtomlinson"
          token: "${{ secrets.BOT_TOKEN }}"
          labels: |
            automerge
            ci
          branch: "upgrade-k8s-version"
          body: |
            A new Kubernetes version has been detected.

            Updated CI and README badges.
