name: "Update Kubernetes"
on:
  schedule:
    - cron:  '30 2 * * *'
  workflow_dispatch: {}
  pull_request:
    paths:
      - .github/workflows/update-kubernetes.yaml
      - ci/update-kubernetes.py

jobs:
  update-kubernetes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Update Kubernetes
        run: uv run ./ci/update-kubernetes.py
      - name: Show diff
        id: diff
        run: |
          echo 'diff<<EOF' >> $GITHUB_OUTPUT
          git diff | tee -a $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
          if [ -z "$(git diff)" ]; then
            echo "No changes to commit"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "Changes to commit"
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi
      - name: Generate PR title
        uses: ai-action/ollama-action@v1
        if: steps.diff.outputs.has_changes == 'true'
        id: title-llm
        with:
          model: llama3.2
          prompt: |
            You are a helpful assistant that generates PR titles for Kubernetes version updates.
            The title should be concise and to the point, and should not include any markdown formatting.
            The title should be in the format of "Update Kubernetes version: remove 1.27" or similar.
            The title should be in the present tense.
            Your response must be no more than 50 characters.

            Here is a diff of the changes:
            
            ```
            ${{ steps.diff.outputs.diff }}
            ```
            Please generate a PR title with particular attention to the Kubernetes version that is being updated.

      - name: Show PR title
        if: steps.diff.outputs.has_changes == 'true'
        run: |
          echo "The action would generate the following PR title: ${{ steps.title-llm.outputs.response }}"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        if: steps.diff.outputs.has_changes == 'true' && github.repository == 'kr8s-org/kr8s' && github.ref == 'refs/heads/main'
        with:
          base: main
          commit-message: ${{ steps.title-llm.outputs.response }}
          title: ${{ steps.title-llm.outputs.response }}
          reviewers: "jacobtomlinson"
          token: "${{ secrets.BOT_TOKEN }}"
          labels: |
            automerge
            ci
          branch: "upgrade-k8s-version"
          body: |
            A new Kubernetes version has been detected.

            Updated CI and README badges.
